import ScienceFiction from '../assets/ecos.png';
import Mystery from "../assets/mist.png";
import Fantasy from "../assets/paradox (1).png";
import { MdOutlineKeyboardDoubleArrowRight } from "react-icons/md";

const books = [
    {
        title: "Science Fiction",
        description: "As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands...",
        image: ScienceFiction
    },
    {
        title: "Mystery",
        description: "The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light...",
        image: Mystery
    },
    {
        title: "Fantasy",
        description: "The ancient prophecy spoke of a child born with starlight in their eyes. As the comet blazed overhead, the kingdom held its breath...",
        image: Fantasy
    },
]

const SampleBooks = () => {
    return (
        <div className="mt-20 text-primary">
            <div className="text-center">
                <h3 className="text-2xl font-bold">Sample Books Generated by BookAI</h3>
                <p className="mt-4 text-secondary">Explore some of the captivating books created using our AI technology.</p>
            </div>
            <div className="mt-12 grid md:grid-cols-2 place-content-center lg:grid-cols-3 gap-8">
                {
                    books.map((book, idx) => (
                        <div key={idx} className='group max-w-[360px] relative isolate p-4 bg-white/5 rounded-lg'>
                            <div className='justify-center rounded-lg overflow-hidden'><img src={book.image} alt={book.title} /></div>
                            <div className="absolute inset-0 top-[50%] duration-300 bg-gradient-to-b from-transparent to-black/50 opacity-0 group-hover:opacity-100 z-10"></div>
                            <div className='absolute bottom-8 z-10 left-8 right-8 opacity-0 transition-all duration-300 translate-y-4 group-hover:opacity-100 group-hover:translate-y-0'>
                                <h4 className='text-xl font-bold'>{book.title}</h4>
                                <p className="mt-2 text-secondary text-sm">"{book.description}"</p>
                                <button className='mt-2 font-medium text-emerald-500 text-sm cursor-pointer flex items-center'><span>
                                    Read More</span> <MdOutlineKeyboardDoubleArrowRight className='w-5 h-5' /></button>
                            </div>
                        </div>
                    ))
                }
            </div>
        </div>
    )
}

export default SampleBooks